## Interview Questions

## Python Data Structure
    1. List
    2. Tuple
    3. Dictionary
    4. String
    5. Basic Programing
    6. Numpy
    7. Pandas
    8. oops
    9. file handling

### Q1. Make the list 3,4,5,6,7,89,10 
### Q2. Concat the following 
    a= 1,2,4,10,30
    b = [4,5,6]

In [1]:
a = [3,4,3,4,5,6,7,89,10]
print(type(a))

<class 'list'>


In [2]:
a = 1,2,4,10,30
b = [4,5,6,'Hi','Hello']
print(list(a)+b)

[1, 2, 4, 10, 30, 4, 5, 6, 'Hi', 'Hello']


### Q3. Reverse the word in the sentence
    strings = "Hi i am Python"


In [3]:
strings = "Hi i am Python"
strings.split()[::-1]

['Python', 'am', 'i', 'Hi']

### Q4. Delete the 1st  Matching element from the lsit
        [2,3,4,9,7,5,4]

In [4]:
a=[2,3,4,9,7,5,4]
a.remove(4)
print(a)

[2, 3, 9, 7, 5, 4]


### Q5. Delete 4 from list and return the values
        [2,3,4,9,7,5,4]

In [5]:
x =  [2,3,4,9,7,5,4]
print("Return the delete value : ",x.pop(2)) # pop take the index values as a input and remove the element from list and return the element
print("List after the pop :",x)

Return the delete value :  4
List after the pop : [2, 3, 9, 7, 5, 4]


### Q5. Insert the 5 on index number 6 in the list b
        b = [3,4,2,1,9,10,23,12,5]

In [6]:
b = [3,4,2,1,9,10,23,12,5]
b.insert(6,5)
print("After the insert operations:",b)

After the insert operations: [3, 4, 2, 1, 9, 10, 5, 23, 12, 5]


### Concat the tuple a and tuple b
        a= ('a',20,40,100,'Hi')
        b=(40,10,3)

In [7]:
a= ('a',20,40,100,'Hi')
b=(40,10,3)
print("Concat Tuple a & Tuple b: ",a+b)

Concat Tuple a & Tuple b:  ('a', 20, 40, 100, 'Hi', 40, 10, 3)


### Diffrence between tuple and list
    

### Reverse the dictionary

In [8]:
dictionary = {'A':10,'B':5,'C':20,'D':10}
new_dict = [{value:key} for key,value in dictionary.items()]

In [9]:
print(new_dict)

[{10: 'A'}, {5: 'B'}, {20: 'C'}, {10: 'D'}]


### You have given a string, You have to find the subset of string and replace the string with given string 
        string="aaaa aabb aba aabbaa abcabc bbccaaabbcc abcdaabcd"
        find_in_str="aa"
        replace_wth="Z"
        
        you should be like : zz zbb aba zbbz abcabc bbcczbbcc zbcdzbcd
        

In [10]:
string="aaaa aabb aba aabbaa abcabc bbccaaabbcc abcdaabcd"
find_in_str="aa"
replace_with="Z"

In [11]:
def find_replace(strings,find_in_str,replace_with):
    len_s = len(strings)
    len_r = len(find_in_str)
    No =len_s-len_r
    for i in range(No):
        if find_in_str in strings[i:i+len_r]:
            strings = strings.replace(strings[i:i+len_r],replace_with)
        else:
            pass
    return strings

In [12]:
find_replace(string,find_in_str,replace_with)

'ZZ Zbb aba ZbbZ abcabc bbccZabbcc abcdZbcd'

## Write a function for Counting Table (From 2 to 20)

In [13]:
def count_table(num):
    for  i in range(1,11):
        print(num,'X',i,'=',num*i)
    return ' '

In [14]:
for i in range(2,21):
    print(count_table(i),end='\n')

2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18
2 X 10 = 20
 
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
3 X 10 = 30
 
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36
4 X 10 = 40
 
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50
 
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54
6 X 10 = 60
 
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
7 X 10 = 70
 
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5 = 40
8 X 6 = 48
8 X 7 = 56
8 X 8 = 64
8 X 9 = 72
8 X 10 = 80
 
9 X 1 = 9
9 X 2 = 18
9 X 3 = 27
9 X 4 = 36
9 X 5 = 45
9 X 6 = 54
9 X 7 = 63
9 X 8 = 72
9 X 9 = 81
9 X 10 = 90
 
10 X 1 = 10
10 X 2 = 20
10 X 3 = 30
10 X 4 = 40
10 X 5 = 50
10 X 6 = 60
10 X 7 = 70
10 X 8 = 80
10 X 9 = 90
10

### Sum the 1st 5 prime numbers

#### you have given n numbers, you have to write a function that can sum first 5 prime numbers  

In [15]:
def sumPrime_num(n):
    count=0
    sums =0
    for num in range(2,n+1):
        j=1
        for i in range(2,num):
            if num%i==0:
                j=num
        if j!=num:
            sums += num
            count +=1
            if count==5:
                    break;
    return sums

In [16]:
print("Sum of 1st 5 prime numbers : ",sumPrime_num(20))

Sum of 1st 5 prime numbers :  28


In [17]:
def prime_num(n):
    sums=0
    count=0
    for num in range(0,n):
        if num>1:
            for i in range(2,num):
                if num%i==0:
                    break
            else:
                count +=1
                sums +=num
                
                if count==5:
                    break
    return sums

In [18]:
print("Sum of 1st 5 prime numbers :", prime_num(20))

Sum of 1st 5 prime numbers : 28


### you have given n numbers, you have to write a code that can Return True if it is prime numbers.


In [19]:
def check_prime(n):
    if n<=1:
        return False
    for i in range(2,n):
        if n%i==0:
            return False
        
    return True

In [20]:
print(check_prime(6))

False


### Find the factorial of n using recursion

In [21]:
def factorial(n):
    if n==1 or n==0:
        return 1 
    else:
        return n*factorial(n-1)

In [22]:
print("factorial of 5:",factorial(5))

factorial of 5: 120


### Numpy

In [23]:
import numpy as np
import random

In [24]:
b=np.random.randint(1,20,5)

In [25]:
zero_matrix=np.zeros(shape=(5,5))

In [26]:
zero_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# use of vstack

In [28]:
ab=np.vstack([zero_matrix,b])

In [29]:
# Columns stack
ac= np.column_stack([zero_matrix,b])

In [30]:
ac

array([[ 0.,  0.,  0.,  0.,  0., 14.],
       [ 0.,  0.,  0.,  0.,  0., 15.],
       [ 0.,  0.,  0.,  0.,  0.,  3.],
       [ 0.,  0.,  0.,  0.,  0.,  3.],
       [ 0.,  0.,  0.,  0.,  0., 12.]])

In [31]:
a=np.random.randint(10,20,5)
ac= np.hstack([a,b])

In [32]:
print('A :',a)
print('B :',b)
print('hstack:', ac)

A : [14 19 16 13 12]
B : [14 15  3  3 12]
hstack: [14 19 16 13 12 14 15  3  3 12]


In [33]:
print(np.vstack([a,b]))

[[14 19 16 13 12]
 [14 15  3  3 12]]


In [34]:
print(np.column_stack([a,b]))

[[14 14]
 [19 15]
 [16  3]
 [13  3]
 [12 12]]


In [35]:
np.diagonal(np.column_stack([a,b]))

array([14, 15])

### Pandas 

In [36]:
import pandas as pd

In [37]:
df = pd.DataFrame({ 'A': [1,2,3,4], 
                   'B': [10,20,30,40],
                   'C': [20,40,60,80]
                  }, 
                  index=['Row 1', 'Row 2', 'Row 3', 'Row 4'])


In [38]:
# Pandas series

In [39]:
type(df.A)

pandas.core.series.Series

In [40]:
print('Pandas Series : \n',pd.Series([3,4,5,6,7]))

Pandas Series : 
 0    3
1    4
2    5
3    6
4    7
dtype: int64


In [41]:
df

A   B   C
Row 1  1  10  20
Row 2  2  20  40
Row 3  3  30  60
Row 4  4  40  80

In [42]:
## Sum the 1st 2 columns and make another columns to store the values
### Apply work on both pandas series and pandas Dataframe
def sum_col(col):
    return [col['A']+col['B']]
df['Sum_ColA+ColB']=df.apply(sum_col,axis=1,result_type='expand')

In [43]:
df

A   B   C  Sum_ColA+ColB
Row 1  1  10  20             11
Row 2  2  20  40             22
Row 3  3  30  60             33
Row 4  4  40  80             44

In [44]:
def pro_col(col):
    return [col['A']*col['B']]

In [45]:
df['Pro_ColA+ColB']=df.apply(pro_col,axis=1,result_type='expand')

In [46]:
df

A   B   C  Sum_ColA+ColB  Pro_ColA+ColB
Row 1  1  10  20             11             10
Row 2  2  20  40             22             40
Row 3  3  30  60             33             90
Row 4  4  40  80             44            160

In [47]:
### Sum the all columns values and store in another raw

In [48]:
df.loc['Total Sum']=df.apply(lambda x:x.sum())

In [49]:
df

A    B    C  Sum_ColA+ColB  Pro_ColA+ColB
Row 1       1   10   20             11             10
Row 2       2   20   40             22             40
Row 3       3   30   60             33             90
Row 4       4   40   80             44            160
Total Sum  10  100  200            110            300

### Sum the all row values and store in another columns values

In [50]:
df['Total_sum']=df.apply(lambda x:x.sum(),axis=1)

In [51]:
df

A    B    C  Sum_ColA+ColB  Pro_ColA+ColB  Total_sum
Row 1       1   10   20             11             10         52
Row 2       2   20   40             22             40        124
Row 3       3   30   60             33             90        216
Row 4       4   40   80             44            160        328
Total Sum  10  100  200            110            300        720

### Use Applymap

In [52]:
data = {
  "name": ["Sally","Mary","John"],
  "city": ["London", "Tokyo", "Madrid"]
}

df_str = pd.DataFrame(data)
### Applymap function work on dataframe only but it performed element-wise operation 

In [53]:
df_str1=df_str.applymap(lambda x:x.upper())

In [54]:
df_str1

name    city
0  SALLY  LONDON
1   MARY   TOKYO
2   JOHN  MADRID

In [55]:
df_str

name    city
0  Sally  London
1   Mary   Tokyo
2   John  Madrid

In [56]:
def concat(row):
    return row['name']+row['city']
df_str['Name_city']=df_str.apply(concat,axis=1,result_type='expand')

In [57]:
df_= df_str.applymap(lambda x: x+' Gupta')

In [58]:
df_.head()

name          city          Name_city
0  Sally Gupta  London Gupta  SallyLondon Gupta
1   Mary Gupta   Tokyo Gupta    MaryTokyo Gupta
2   John Gupta  Madrid Gupta   JohnMadrid Gupta

In [59]:
df_=df.applymap(lambda x:x+10)

In [60]:
df_

A    B    C  Sum_ColA+ColB  Pro_ColA+ColB  Total_sum
Row 1      11   20   30             21             20         62
Row 2      12   30   50             32             50        134
Row 3      13   40   70             43            100        226
Row 4      14   50   90             54            170        338
Total Sum  20  110  210            120            310        730

### PIPE in pandas

    Pipe is a method in pandas.DataFrame capable of passing existing functions from packages or self-defined functions to dataframe. It is part of the methods that enable method chaining. By using pipe, multiple processes can be combined with method chaining without nesting. Let’s look into an example here to show its benefits.

    In the documentation of pandas, there are 3 functions: h(df), g(df,arg1=a), f(df,arg2=b, arg3=c) applied on df in this order. Usually, three functions are nested in the sequence of calling. It is hard to read the functions & arguments at first glance. By method chaining, the relationships among operations can be shown in a clearer format.

In [61]:
df_data = pd.DataFrame({
    'name': ['Ted'] * 3 + ['Lisa'] * 3 + ['Sam'] * 3,
    'subject': ['math', 'physics', 'history'] * 3,
    'score': np.random.randint(60, 100, 9)
})

In [62]:
df_data

name  subject  score
0   Ted     math     60
1   Ted  physics     77
2   Ted  history     62
3  Lisa     math     65
4  Lisa  physics     68
5  Lisa  history     64
6   Sam     math     98
7   Sam  physics     77
8   Sam  history     61

    Return pandas dataframe
    The goal is to get the rank of every subject in one line and append it to the original dataframe. Thus, a function - get_subject_rank - is created to complete this task. By passing the functions, the rank is appended to the original dataframe.

In [63]:
def subject_rank(df):
    df=df.copy()
    df['Subject_Rank']=(df.groupby(['subject'])['score'].rank(ascending=False))
    return df

In [64]:
def new_score(df,add_score):
    df = df.copy()
    df=df.assign(new_score=lambda x: x.score+add_score)
    return df

In [65]:
df_data.pipe(subject_rank).pipe(new_score,2)

name  subject  score  Subject_Rank  new_score
0   Ted     math     60           3.0         62
1   Ted  physics     77           1.5         79
2   Ted  history     62           2.0         64
3  Lisa     math     65           2.0         67
4  Lisa  physics     68           3.0         70
5  Lisa  history     64           1.0         66
6   Sam     math     98           1.0        100
7   Sam  physics     77           1.5         79
8   Sam  history     61           3.0         63

### Map function
###### The map() function executes a specified function for each item in an iterable. The item is sent to the function as a parameter.

In [66]:
def concat(a, b):
    return a + b
x = list(map(concat, ('apple ', 'banana ', 'cherry '), (' orange', ' lemon', ' pineapple')))


In [67]:
list(x)

['apple  orange', 'banana  lemon', 'cherry  pineapple']

### find the sqrt of the given number using map and lambda functions

In [68]:
no = [16,25,36,49,64,81]
list(map(lambda x:np.sqrt(x),no))

[4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [69]:
# square the given numbers
No=[2,3,4,5,6,7]
list(map(lambda x:x**2,No))

[4, 9, 16, 25, 36, 49]

### Reduce 
##### Use reduce function to sum the given element

In [70]:
from functools import reduce

In [71]:
reduce(lambda x,y:x+y,No) # reduce function return single values from list 

27

In [72]:
### Find the maximum element from the list
No=[2,3,4,5,6,7]
reduce(lambda x,y: x if x>y else y,No)

7

In [73]:
### Filter functions
### use filter function and find the even numbers
def check_even(n):
    if n>1:
        if n%2==0:
            return True
        else:
            return False

In [74]:
list(filter(check_even,[1,2,3,6,7,8,9]))

[2, 6, 8]

In [75]:
### use filter function and find the prime numbers
list(filter(check_prime,[1,2,3,6,7,8,9]))

[2, 3, 7]